### ISSUE TITLE
Steps to install PGG_meteor

### ISSUE THREAD

**Issue by enfascination** [cosanlab/PGG_meteor#1]
git clone https://github.com/cosanlab/PGG_meteor.git -b allConds
cd PGG_meteor
git clone https://github.com/TurkServer/turkserver-meteor.git packages/turkserver
meteor add mizzao:turkserver
<you need to provide a settings.json.min with a password and your weird lobby setting>
cp settings.json.min settings.json
meteor add iron:middleware-stack@=1.1.0
meteor run --settings=settings.json
<browse to http://localhost:3002/turkserver/>
<at http://localhost:3002/turkserver/ filter for allConds>
<at http://localhost:3002/turkserver/ click Manage>
<at http://localhost:3002/turkserver/ add a treatment and press plus>

**Comment by ejolly** [comment]
Should be covered with the latest commit and update to README
